import type React from 'react';
import {
  Activity,
  AlarmClock,
  Ambulance,
  BadgeCheck,
  Ban,
  BatteryCharging,
  BedDouble,
  Bell,
  Blocks,
  BookHeart,
  Brain,
  Building2,
  CalendarDays,
  CalendarRange,
  ClipboardList,
  Database,
  FileCheck2,
  FilePlus2,
  FlaskConical,
  FolderOpen,
  Gem,
  HeartPulse,
  Images,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListChecks,
  Mail,
  MapPin,
  MessageSquare,
  NotebookText,
  Palette,
  Pill,
  ScanLine,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Stethoscope,
  Syringe,
  TestTubes,
  Timer,
  Bone,
  Trash2,
  User,
  Users,
  Vibrate,
  Waves,
  Zap,
} from 'lucide-react';

const MAP: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  Activity,
  AlarmClock,
  Ambulance,
  BadgeCheck,
  Ban,
  BatteryCharging,
  BedDouble,
  Bell,
  Blocks,
  BookHeart,
  Brain,
  Building2,
  CalendarDays,
  CalendarRange,
  ClipboardList,
  Database,
  FileCheck2,
  FilePlus2,
  FlaskConical,
  FolderOpen,
  Gem,
  HeartPulse,
  Images,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListChecks,
  Mail,
  MapPin,
  MessageSquare,
  NotebookText,
  Palette,
  Pill,
  ScanLine,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Stethoscope,
  Syringe,
  TestTubes,
  Timer,
  Bone,
  Trash2,
  User,
  Users,
  Vibrate,
  Waves,
  Zap,
};

export function iconFor(name: string | null | undefined, fallback: React.ComponentType<{ size?: number; className?: string }> = FileCheck2): React.ComponentType<{ size?: number; className?: string }> {
  if (!name) return fallback;
  return MAP[name] ?? fallback;
}

/** Icônes par préfixe de catégorie (couleur via CSS variable de la catégorie). */
export const CAT_ICON: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  LAB: TestTubes,
  PHA: Pill,
  DIA: Activity,
  CAR: HeartPulse,
  RAD: ScanLine,
  CON: Stethoscope,
  SPE: BookHeart,
  GYP: Gem,
  CHI: Vibrate,
  SOI: Waves,
  ANA: Brain,
  REE: Blocks,
  CER: BatteryCharging,
  ORD: NotebookText,
};
